services:

  datastream:
    build:
      context: .
    restart: always
    ports:
      - 4041:4041
    entrypoint:
      [
        "python", "-m", "uvicorn",
        "--host", "0.0.0.0",
        "--port", "4041",
        "api:api",
        "--reload"
      ]
