services:
  
  pg-datagen:
    build:
      context: ./trino/pg/datagen
    volumes:
      - pg-data-vol:/data

  pg-db:
    image: postgres:16.0-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    volumes:
      - pg-data-vol:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    depends_on:
      - pg-datagen

volumes:
  pg-data-vol: