name: 'music_o_set'
version: '1.0.0'

profile: 'music_o_set'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  music_o_set:
    musicoset_metadata:
      +delimiter: "\t"
      tables:
        - name: albums
        - name: artists
        - name: releases
        - name: songs
        - name: tracks
        
    musicoset_popularity:
      +delimiter: "\t"
      tables:
        - name: album_chart
        - name: album_pop
        - name: artist_chart
        - name: artist_pop
        - name: song_chart
        - name: song_pop

models:
  music_o_set:
