services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: admin
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: example
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  # Generate data and use pg db.
  datagen:
    build:
      context: datagen
    volumes:
      - data-vol:/data

  db:
    image: postgres:16.0-alpine3.17
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    volumes:
      - data-vol:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432  # !!
    networks:
      - metanet1
    depends_on:
      - datagen

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data-vol:

networks:
  metanet1:
    driver: bridge