services:
  
  datagen:
    build:
      context: datagen
    volumes:
      - data-vol:/data

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    volumes:
      - data-vol:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    depends_on:
      - datagen

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data-vol: