services:

  example_api:
    build:
      context: ./example_api
    restart: always
    ports:
      - 8001:8001
    entrypoint:
      [
        "python", "-m", "uvicorn",
        "--host", "0.0.0.0",
        "--port", "8001",
        "api:api",
        "--reload"
      ]
