version: '3.1'
services:
  datastream:
    build:
      context: ../../..
      dockerfile: ./toys/ds_models/sensor_event_model/Dockerfile
    restart: always

    ports:
      - 4042:4042
    entrypoint:
      [
        "/app/.venv/bin/python",
        "-m",
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "4042",
        "toys.ds_models.sensor_event_model.api:api",
        "--reload"
      ]
