config:
  use_colors: True

dbt_pg:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: example
      port: 5432
      dbname: postgres
      schema: public
